/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidateRouteImport } from './routes/validate'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsBookingIdRouteImport } from './routes/tickets_.$bookingId'
import { Route as EventsCreateRouteImport } from './routes/events_.create'
import { Route as EventsEventIdRouteImport } from './routes/events_.$eventId'
import { Route as BookingsNewRouteImport } from './routes/bookings_.new'
import { Route as BookingsNewSuccessRouteImport } from './routes/bookings_.new_.success'

const ValidateRoute = ValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsBookingIdRoute = TicketsBookingIdRouteImport.update({
  id: '/tickets_/$bookingId',
  path: '/tickets/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events_/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings_/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewSuccessRoute = BookingsNewSuccessRouteImport.update({
  id: '/bookings_/new_/success',
  path: '/bookings/new/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/events': typeof EventsRoute
  '/sales': typeof SalesRoute
  '/validate': typeof ValidateRoute
  '/bookings/new': typeof BookingsNewRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/tickets/$bookingId': typeof TicketsBookingIdRoute
  '/bookings/new/success': typeof BookingsNewSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/events': typeof EventsRoute
  '/sales': typeof SalesRoute
  '/validate': typeof ValidateRoute
  '/bookings/new': typeof BookingsNewRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/tickets/$bookingId': typeof TicketsBookingIdRoute
  '/bookings/new/success': typeof BookingsNewSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/events': typeof EventsRoute
  '/sales': typeof SalesRoute
  '/validate': typeof ValidateRoute
  '/bookings_/new': typeof BookingsNewRoute
  '/events_/$eventId': typeof EventsEventIdRoute
  '/events_/create': typeof EventsCreateRoute
  '/tickets_/$bookingId': typeof TicketsBookingIdRoute
  '/bookings_/new_/success': typeof BookingsNewSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/events'
    | '/sales'
    | '/validate'
    | '/bookings/new'
    | '/events/$eventId'
    | '/events/create'
    | '/tickets/$bookingId'
    | '/bookings/new/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/events'
    | '/sales'
    | '/validate'
    | '/bookings/new'
    | '/events/$eventId'
    | '/events/create'
    | '/tickets/$bookingId'
    | '/bookings/new/success'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/events'
    | '/sales'
    | '/validate'
    | '/bookings_/new'
    | '/events_/$eventId'
    | '/events_/create'
    | '/tickets_/$bookingId'
    | '/bookings_/new_/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  EventsRoute: typeof EventsRoute
  SalesRoute: typeof SalesRoute
  ValidateRoute: typeof ValidateRoute
  BookingsNewRoute: typeof BookingsNewRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsCreateRoute: typeof EventsCreateRoute
  TicketsBookingIdRoute: typeof TicketsBookingIdRoute
  BookingsNewSuccessRoute: typeof BookingsNewSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets_/$bookingId': {
      id: '/tickets_/$bookingId'
      path: '/tickets/$bookingId'
      fullPath: '/tickets/$bookingId'
      preLoaderRoute: typeof TicketsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/create': {
      id: '/events_/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId': {
      id: '/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings_/new': {
      id: '/bookings_/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings_/new_/success': {
      id: '/bookings_/new_/success'
      path: '/bookings/new/success'
      fullPath: '/bookings/new/success'
      preLoaderRoute: typeof BookingsNewSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  EventsRoute: EventsRoute,
  SalesRoute: SalesRoute,
  ValidateRoute: ValidateRoute,
  BookingsNewRoute: BookingsNewRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsCreateRoute: EventsCreateRoute,
  TicketsBookingIdRoute: TicketsBookingIdRoute,
  BookingsNewSuccessRoute: BookingsNewSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
