name: Deploy Backend

on:
  push:
    branches:
      - main
    # a pull request that merged into main will trigger the push event
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      id-token: write # this will issue the OIDC token for Workload Identity Federation
    defaults:
      run:
        working-directory: backend

    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      REPO_NAME: ${{ vars.GCP_ARTIFACT_REPOSITORY_NAME }}
      IMAGE_NAME: backend
      DEPLOYER_IDENTITY: github-deployer # the Service Account that will push the image and create the Cloud Run service
      SERVICE_NAME: fast-ticket-backend
      SERVICE_RUNTIME_IDENTITY: cloud-run-runtime # the Service Account that the Cloud Run service itself will use

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          # $VAR won't resolve inside with: blocks, must use GitHub expression syntax here
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ env.DEPLOYER_IDENTITY }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      # When the auth@v3 action runs, it's not immediately talking to Google. First it calls back to GitHub itself, using the ACTIONS_ID_TOKEN_REQUEST_URL and ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variables that GitHub automatically injects into every job (this requires permissions: id-token: write in your workflow — otherwise this step fails). The action asks GitHub's OIDC token endpoint: "give me an ID token, and set the audience to Google's STS endpoint."
      # STS = Security Token Service, which powers Workload Identity Federation
      # GitHub's servers generate a JWT, sign it with GitHub's private key, and return it
      # The auth action now makes an HTTPS call to https://sts.googleapis.com/v1/token, passing the GitHub JWT as the subject_token, along with the WIF provider resource path (your WIF_PROVIDER value) telling Google which provider config to validate against.

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build image
        run: |
          docker build \
          -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA \
          .

      - name: Push image
        run: |
          docker push \
          $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
          --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA
