name: Deploy Frontend

on:
  push:
    branches:
      - main
    # a pull request that merged into main will trigger the push event
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: frontend

    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      REPO_NAME: ${{ vars.GCP_ARTIFACT_REPOSITORY_NAME }}
      IMAGE_NAME: frontend
      DEPLOYER_IDENTITY: github-deployer  # the Service Account that will push the image and create the Cloud Run service
      SERVICE_NAME: fast-ticket-frontend
      SERVICE_RUNTIME_IDENTITY: cloud-run-runtime  # the Service Account that the Cloud Run service itself will use

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          # $VAR won't resolve inside with: blocks, must use GitHub expression syntax here
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ env.DEPLOYER_IDENTITY }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build image
        run: |
          docker build \
          -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA \
          .

      - name: Push image
        run: |
          docker push \
          $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
          --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA \
          --service-account=$SERVICE_RUNTIME_IDENTITY@$PROJECT_ID.iam.gserviceaccount.com \
          --region=$REGION \
          --min=0 \
          --max=1 \
          --min-instances='default' \
          --max-instances='default' \
          --port=80 \
          --concurrency=1000 \
          --cpu=1 \
          --memory=512Mi \
          --cpu-boost \
          --no-invoker-iam-check \
          --timeout=30 \
          --startup-probe=initialDelaySeconds=10,timeoutSeconds=3,periodSeconds=10,failureThreshold=3,httpGet.path=/health,httpGet.port=80 \
          --liveness-probe=initialDelaySeconds=10,timeoutSeconds=3,periodSeconds=10,failureThreshold=3,httpGet.path=/health,httpGet.port=80